name: Cypress Tests

on:

 push:

   branches:

     - main

jobs:

 cypress-run:

   runs-on: ubuntu-latest

   strategy:

     fail-fast: false

   steps:

     - name: Checkout

       uses: actions/checkout@v4

     # Limpar o cache antes de instalar dependências
     - name: Clear Cypress Cache
       
       run: rm -rf ~/.cache/Cypress

     - name: Start Server BackEnd

       run: |

         cd server

         npm install

         npm start &

         until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ]; do

           echo "Waiting for server to start..."

           sleep 1

         done

         echo "Server is running successfully."

       working-directory: server

     - name: Start Web App FrontEnd

       run: |

         cd web

         npm install

         npm start &

     - name: Install Cypress Dependencies         
       run: |

        npm ci

     - name: Run Cypress Tests

       uses: cypress-io/github-action@v6

       with:

         spec: cypress/e2e/{cadastro-sucesso.cy.js,login-correto.cy.js,dashborad-teste.cy.js}

         wait-on: 'http://localhost:3000,http://localhost:8080'

         record: false
